import type { Request } from 'express';
import type { ActorType, AuthType } from '../enums/auth-type.enum';

/**
 * Request-scoped principal and tenancy contracts.
 *
 * These describe the objects the authentication and organization-context guards
 * attach to the Express request. They are intentionally plain projections rather
 * than TypeORM entities: the guards must not leak lazy relations or password
 * hashes into controller code, and a narrow shape makes it obvious what is
 * actually available downstream.
 */

/** The authenticated human user behind a Bearer request. */
export interface AuthenticatedUser {
  id: string;
  email: string;
  displayName: string;
  isPlatformAdmin: boolean;
  emailVerified: boolean;
  /** Session id from the access token, used to scope sign-out. */
  sessionId: string;
  /** Access token id, used to revoke this specific token. */
  tokenId: string;
}

/** The machine principal behind an `X-API-Key` request. */
export interface AuthenticatedApiKey {
  id: string;
  name: string;
  /** Public, non-secret prefix; safe to log. */
  prefix: string;
  organizationId: string;
  /** Scopes granted to the key, already intersected with its creator's authority. */
  scopes: string[];
  /** The user who issued the key. Actions are attributed to the key, not to them. */
  createdById: string;
}

/** The workspace a request is operating inside. */
export interface RequestOrganization {
  id: string;
  slug: string;
  name: string;
  status: string;
}

/** The caller's membership of {@link RequestOrganization}. */
export interface RequestMembership {
  id: string;
  userId: string;
  organizationId: string;
  status: string;
  /** Slugs of every role assigned to this member. */
  roleSlugs: string[];
  /** Highest role priority held, used for "may I act on this member?" checks. */
  highestRolePriority: number;
  isOwner: boolean;
}

/**
 * The fully resolved security context for a request.
 *
 * Exactly one of `user` / `apiKey` is populated for an authenticated request.
 * `organization`, `membership` and `permissions` are populated only once the
 * organization context guard has run, which is why they are optional here.
 */
export interface RequestPrincipal {
  actorType: ActorType;
  /** The id recorded as the actor on audit entries. */
  actorId: string;
  /** A human readable label for the actor, denormalised onto audit entries. */
  actorLabel: string;
  authType: AuthType;
  user?: AuthenticatedUser;
  apiKey?: AuthenticatedApiKey;
}

/**
 * Express request augmented with everything the guards resolve.
 *
 * Controllers should prefer the `@CurrentUser()`, `@CurrentOrganization()` and
 * `@CurrentPermissions()` parameter decorators over reaching into the request
 * directly; this type exists for guards, interceptors and filters.
 */
export interface AuthenticatedRequest extends Request {
  /** Correlation id, generated by the request-context middleware. */
  requestId: string;
  /** Monotonic start timestamp used to compute request duration. */
  startTime: number;
  principal?: RequestPrincipal;
  user?: AuthenticatedUser;
  apiKey?: AuthenticatedApiKey;
  organization?: RequestOrganization;
  membership?: RequestMembership;
  /** Effective permission keys in the current workspace, wildcards included. */
  permissions?: string[];
  authType?: AuthType;
}
