import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryColumn,
} from 'typeorm';
import type { Classification } from '../../knowledge/domain/classification';
import type { Integrity } from '../../tools/domain/information-flow';
import { Conversation } from './conversation.entity';

export enum MessageRole {
  USER = 'USER',
  ASSISTANT = 'ASSISTANT',
}

export enum MessageStatus {
  COMPLETE = 'COMPLETE',
  /** The client disconnected mid-answer; the partial text is kept. */
  CANCELLED = 'CANCELLED',
  /** The model failed or timed out; any partial text is kept. */
  FAILED = 'FAILED',
}

/** A source an answer drew on. Ids only: titles are resolved at read time, under access control. */
export interface MessageCitation {
  tag: string;
  documentId: string;
  chunkId: string;
  knowledgeBaseId: string;
  rank: number;
  score: number;
  /** Whether the answer actually cited it, as opposed to it merely being provided. */
  cited: boolean;
}

/**
 * A tool call made while producing an answer (phase 4). Content-free: which
 * tool, what happened, how long it took — never the arguments or the result.
 */
export interface MessageToolCall {
  executionId: string;
  tool: string;
  status: 'ok' | 'error' | 'denied';
  code?: string;
  reason?: string;
  durationMs: number;
}

/** What the PII engine did for the turn. Counts only — never values. */
export interface MessageRedaction {
  enabled: boolean;
  degraded: boolean;
  entities: number;
  byType: Record<string, number>;
  placeholdersResolved?: number;
  placeholdersUnresolved?: number;
}

/**
 * One message. Content is ciphertext under the conversation's data key,
 * bound by associated data to this message's id.
 *
 * Carries its information-flow label (`classification`, `knowledgeBaseIds`,
 * `documentIds`), checked on every read against the reader's current access.
 */
@Entity('conversation_messages')
@Index('uq_conversation_messages_sequence', ['conversationId', 'sequence'], {
  unique: true,
})
export class ConversationMessage {
  /** Generated by the application so the ciphertext can be bound to it before insert. */
  @PrimaryColumn({ type: 'uuid', name: 'id' })
  id: string;

  @CreateDateColumn({ type: 'timestamptz', name: 'created_at' })
  createdAt: Date;

  @Column({ type: 'uuid', name: 'organization_id' })
  organizationId: string;

  @Column({ type: 'uuid', name: 'conversation_id' })
  conversationId: string;

  @ManyToOne(() => Conversation, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'conversation_id' })
  conversation?: Conversation;

  @Column({ type: 'integer', name: 'sequence' })
  sequence: number;

  @Column({ type: 'varchar', length: 16, name: 'role' })
  role: MessageRole;

  @Column({ type: 'varchar', length: 16, name: 'status' })
  status: MessageStatus;

  @Column({ type: 'text', name: 'content_ciphertext', nullable: true })
  contentCiphertext: string | null;

  @Column({ type: 'integer', name: 'char_count', default: 0 })
  charCount: number;

  @Column({ type: 'integer', name: 'token_count', default: 0 })
  tokenCount: number;

  @Column({ type: 'varchar', length: 16, name: 'classification' })
  classification: Classification;

  @Column({ type: 'jsonb', name: 'knowledge_base_ids', default: () => "'[]'::jsonb" })
  knowledgeBaseIds: string[];

  @Column({ type: 'jsonb', name: 'document_ids', default: () => "'[]'::jsonb" })
  documentIds: string[];

  @Column({ type: 'jsonb', name: 'citations', default: () => "'[]'::jsonb" })
  citations: MessageCitation[];

  /**
   * How far the message can be trusted not to carry attacker-written text: the
   * lowest integrity of what it was derived from (phase 4). Rows from before
   * phase 4 read as INTERNAL.
   */
  @Column({ type: 'varchar', length: 16, name: 'integrity', default: 'INTERNAL' })
  integrity: Integrity;

  @Column({ type: 'jsonb', name: 'tool_calls', default: () => "'[]'::jsonb" })
  toolCalls: MessageToolCall[];

  @Column({ type: 'integer', name: 'agent_version', nullable: true })
  agentVersion: number | null;

  @Column({ type: 'integer', name: 'prompt_template_version', nullable: true })
  promptTemplateVersion: number | null;

  @Column({ type: 'varchar', length: 200, name: 'model', nullable: true })
  model: string | null;

  @Column({ type: 'uuid', name: 'invocation_id', nullable: true })
  invocationId: string | null;

  @Column({ type: 'uuid', name: 'retrieval_id', nullable: true })
  retrievalId: string | null;

  @Column({ type: 'jsonb', name: 'redaction', default: () => "'{}'::jsonb" })
  redaction: MessageRedaction | Record<string, never>;

  @Column({ type: 'varchar', length: 64, name: 'error_code', nullable: true })
  errorCode: string | null;

  /** Client-supplied idempotency key: resending the same message is detected, not duplicated. */
  @Column({ type: 'uuid', name: 'client_message_id', nullable: true })
  clientMessageId: string | null;
}
