import {
  CreateDateColumn,
  DeleteDateColumn,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
  VersionColumn,
} from 'typeorm';

/**
 * Shared column set for every persisted entity.
 *
 * Conventions applied platform-wide:
 *
 *  - **UUID primary keys.** Sequential integers leak volume (how many workspaces
 *    exist, how fast the platform is growing) and make cross-tenant id guessing
 *    trivial. Every id is a v4 UUID generated by PostgreSQL's `gen_random_uuid()`.
 *  - **`timestamptz`, never `timestamp`.** Naive timestamps are the usual cause
 *    of audit trails that drift by an hour twice a year. Everything is stored in
 *    UTC with an explicit zone.
 */
export abstract class BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @CreateDateColumn({ type: 'timestamptz', name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz', name: 'updated_at' })
  updatedAt: Date;
}

/**
 * Base for entities that are archived rather than destroyed.
 *
 * Soft deletion is the default for anything a compliance reviewer might later
 * need to see: a removed member, a deleted agent and a retired API key all
 * remain referenceable from historical audit records. TypeORM automatically
 * excludes soft-deleted rows from `find` unless `withDeleted` is passed.
 *
 * Note that soft deletion interacts with unique constraints — a deleted user's
 * email would otherwise block re-registration — so uniqueness on such columns is
 * enforced with partial indexes (`WHERE deleted_at IS NULL`) in the migration.
 */
export abstract class SoftDeletableEntity extends BaseEntity {
  @DeleteDateColumn({ type: 'timestamptz', name: 'deleted_at', nullable: true })
  deletedAt: Date | null;

  get isDeleted(): boolean {
    return this.deletedAt !== null && this.deletedAt !== undefined;
  }
}

/**
 * Base for entities where concurrent edits must not silently overwrite one
 * another. TypeORM increments `version` on every save and fails the update if
 * the row changed underneath, surfacing an `OptimisticLockVersionMismatchError`
 * instead of a lost update.
 *
 * Applied to role and workflow definitions, where two administrators editing the
 * same permission set at once is a realistic scenario with a real security
 * consequence.
 */
export abstract class VersionedEntity extends SoftDeletableEntity {
  @VersionColumn({ name: 'version', default: 1 })
  version: number;
}
